// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolksCalls.Infra.Data.Context;

namespace VolksCalls.Infra.Data.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20210614181233_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VolksCalls.Domain.Models.CI.CIDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnName("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CIId")
                        .HasColumnName("CIId")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CIName")
                        .HasColumnName("CIName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CallGroup")
                        .HasColumnName("CallGroup")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnName("DateRegister")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnName("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnName("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserDeletedId")
                        .HasColumnName("UserDeletedId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserInsertedId")
                        .HasColumnName("UserInsertedId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserUpdatedId")
                        .HasColumnName("UserUpdatedId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("CI");
                });

            modelBuilder.Entity("VolksCalls.Domain.Models.CallsCategoryDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnName("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("CIId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CallsCategoryParentId")
                        .HasColumnName("CallsCategoryParentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateRegister")
                        .HasColumnName("DateRegister")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateUpdate")
                        .HasColumnName("DateUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnName("DeleteDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Level")
                        .HasColumnName("Level")
                        .HasColumnType("int");

                    b.Property<int>("QtdChildren")
                        .HasColumnName("QtdChildren")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserDeletedId")
                        .HasColumnName("UserDeletedId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserInsertedId")
                        .HasColumnName("UserInsertedId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserUpdatedId")
                        .HasColumnName("UserUpdatedId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CIId");

                    b.HasIndex("CallsCategoryParentId");

                    b.ToTable("TblCallsCategory");
                });

            modelBuilder.Entity("VolksCalls.Domain.Models.CallsCategoryDomain", b =>
                {
                    b.HasOne("VolksCalls.Domain.Models.CI.CIDomain", "CI")
                        .WithMany("CallsCategories")
                        .HasForeignKey("CIId");

                    b.HasOne("VolksCalls.Domain.Models.CallsCategoryDomain", "CallsCategoryParent")
                        .WithMany("CallsCategoriesChildren")
                        .HasForeignKey("CallsCategoryParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
